name: 'Quarkus - Test'

on:
  pull_request:
    branches: ['*']

jobs:
  shared-job:
    uses: extra-red-srl/dpp-pipelines/.github/workflows/quarkus-test.yml@main
    with:
      java_version: '21'
      java_distribution: 'temurin'
      maven_version: '3.9.6'
